import streamlit as st
import joblib
import numpy as np

st.set_page_config(page_title="AI Content Verifier", layout="wide")
st.title("📝 AI-Generated Text Detector & Forensic Analytics Hub")
st.write("Analyze text metrics and linguistic predictability to determine if content was human-authored or generated by an LLM.")

@st.cache_resource
def load_text_forensics():
    model = joblib.load("ai_detector_model.pkl")
    vectorizer = joblib.load("text_vectorizer.pkl")
    return model, vectorizer

try:
    model, vectorizer = load_text_forensics()

    st.subheader("📥 Document Content Submission")
    user_text = st.text_area(
        "Paste the raw text content or essay draft below (Minimum 2-3 sentences recommended):",
        placeholder="Type or paste text content here to run stylistic profiling...",
        height=250
    )

    if st.button("🔍 Run Linguistic Anomaly Scan"):
        if user_text.strip() == "":
            st.warning("Please input text to analyze.")
        else:
            # 1. Map input string to the exact N-gram vector matrix space
            transformed_input = vectorizer.transform([user_text])
            
            # 2. Extract probability distributions
            prediction = model.predict(transformed_input)[0]
            probabilities = model.predict_proba(transformed_input)[0]

            st.markdown("---")
            st.subheader("📋 Forensic Assessment Metrics")
            
            # Create metric tracking visualizations
            col1, col2 = st.columns(2)
            with col1:
                st.metric("Human Authorship Probability", f"{probabilities[0]*100:.2f}%")
            with col2:
                st.metric("LLM Generation Probability", f"{probabilities[1]*100:.2f}%")

            st.markdown("### Final Analysis Verdict")
            if prediction == 1:
                st.error("🚨 CRITICAL WARNING: High Probability of AI-Generated Content!")
                st.warning("⚠️ Stylistic Indicators: The underlying text exhibits a highly predictable structural rhythm, minimal structural variance, and a heavy distribution of standard LLM phrasing markers.")
            else:
                st.success("✅ Content Verified: High Probability of Human Authorship!")
                st.info("The text profile displays natural variations in sentence cadence, vocabulary vocabulary spacing, and linguistic shifts common in native human drafting.")

except FileNotFoundError:
    st.error("❌ Component Error: Missing local model configuration parameters. Run `python train.py` inside this terminal layout first.")